language: node_js
node_js:
- 4.2.3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
before_deploy:
- git config --global user.email "kauabunga@traivs.com"
- git config --global user.name "Kauabunga Travis"
- npm run release
- ls -ltra
deploy:
  app: cpx
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: HpPXhAZvimcOHug9Wm46f1qfwBR59l1G5pUGgc/b0dTTq1tDizOSrA8EKeEMsvzzU9+BZ82IgZc9lGOu8rltPyzabTeeub4rJaNFzXdKyNbsJJhn8SaCuBqR8otVNyGJt7uu3JSTLyAGdUhbLgyIHZUgVElGf9cMHK/LLlFgsJEB9nwqpexrEj/rdax9yLUlLG0gt9+Qd+8fMATKRmUIK2KROEsWcmGUIQ0v+eBjIM6Ed/F2vbuO003rsLf6/a1NV6t+Ovu9QqxFrvSkrOC6cmYEaAngI+hcxXuiR4vxWHfDKviQ2zgLzGbAIWhwTAcFi+tZeDYg6nwwxXaUAOOLrOvo6H4Fi4eBneYwkWbZLDXuQNnl9C6X5JpwXJUQQPbWKGn/DhrGV/CCCHXHAstDTukpHETBWaXEuW6Ahb+eE5PC7AJXY3iN5K+yXU1ukihIg91HWN7lSWX1e70c8Ynpg4nvcJJPEKtA9aTZW8yKEV4U8kvY7NqvP2EUGvW1N4kfsmlHN+Ws+8OCz9kjMn4pgfG6KWd8mFHFl7WpubaaFv3kt1PgdwHWUt/6Rx3j9fFm9b+eLGX5+OwjVuRVd7g3voLHJBYXc4YzcT33YcFyuYX8wu34+COZi7yRvkYzlz9dfdrPpgwiZsH6nxdeiL4efik/YILIJcKCA5hu0EGmPGI=
addons:
  sauce_connect:
    username: Kauabunga
    access_key:
      secure: KBdM8o38jlwbMbPzfuYXnYDTkZxOEzFdF2OWwmmN62SLeJnZ6izkqSE9jgJYPyQEIB8KzoTWm5vverEl65+Fn4Lr/p1OvEigm2Ot9+vDkyIr1jqTehvsFA7Fo7oNalgyJeI9kfTcajhtXTp8A57fUFCAMvUE60hKY6LZls2MMqW4RQ9TspOP9im/8T4c2ghxwuczgehM9QP0xzfD4Y9zLDitUjtZPl+fKj/Ou4aluQ7u1TDXnsRC7exQtDSbnqfZJ1i50g2I4wp5VVkqr+p/kwg5Uy6zD2+jjib2dg6dTvwM5BL/qWGyJm1mRk7xoB/zjJr8O6nAU/busAk6xDviW715/1fioyvrOUVCGrL6459Ie7mnF/nZKTbU4R7VTtaNXHcSVSdq6q+7ilyUJjiTVIwa3dmwho9jOx5Kk99xHN2L8sCcTikMGYadtdIWRM5dGumC+nkHzFaxKcpUvuTvZAbBtHtrG+VpgpDlr8XhVXarXUnporh1yVUATlkuSfEIImFNbPQS1sJyd6HbfWy2wWIJJ5HFPnPidjkQxmz4cW3EhWLp2z2drnAhNzSLGC5lEd/t3+rd6X3QfKvmIzZ890RuKtjDQGWtll+yW9MJrcfLxF2yeYDew3NufULA8R1INjJFGoWfG4cQWRlb4XnWyFihXqJJBd1RNtCoM4sxyuo=
env:
  global:
  - secure: jTcw1RzQgbqJbdWIkVhA9SsCe8+7OUYE6dnVMeEUiz1FGom6iFo0uWhNQewRDZ27vwI9V6q9DkRPmZJWeqYs7NhrRvvCVeGuOiygWiENXGiZtFI8+LGnu28/IAF+rRzJ8bwyUXRWcQDXx8cX0tLZA8rl8KHydHryupT204cLzFKV0VSfoy8YDu6aao+9XVDSwJ4lJU0GvM2n9t2vF/DKEF9lkZ+2Rp7Zgltyfq/sb5nZIys5pqfrBIc3XVsGMVf3tQzfv96FIcmgD1+bN9w8uAjO5xdE48EELYCmcVjpS0fEZnymbek2++YmYGomH94+VS8Yy+3x4lePhRaKljMstPy14FzB33xxN7AYzC3uXzLb8lbZ4chUm606L4zVCCjD96iShRTEQhzOq5YyihbK9jH/biylxvd8xHUonQ/zxRJUNApzxuFBWShUd3fEG+NT/Q3k05xZa7epsHyj9wgfijJ18E22d+NAZPcAFohUXtp81GdUDBcKzTEJxOmADfD53hHEBlJwth7lENGWdGZZLD9qCFXpN/jIcQL/xZAgKhUH5XftAQuBxCduzzEQcoJnMWGROz6iDSXLvImgYCXAPHWvN/Cwk/RL9uHQ9z7dXmCoX8y59m5eRXJUEloFfuE44Xn3hszIpydDYC6dBphyJDJSHgJuVlusvNI51ZMaBOs=
